name: Android CI

on:
  push:
    branches: [ CI/CD ]
  pull_request:
    branches: [ CI/CD ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/upload-artifact@v4
        name: "Upload Node Modules - v4"
        with:
          name: node_modules-v4
          path: node_modules
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Create .env file
        run: echo "API_KEY=${{ secrets.API_KEY }}" > .env

      - name: Build project
        run: ./gradlew assembleDebug

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/reports